Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          targetOptions:

            # split published urls into folders to avoid
            # running into fs folder limits
            subdivideHashPathSegment: true

            # use relative links to allow putting of
            # Web/_Resources/Persistent into the shared
            # folder for faster deployments
            relativeSymlinks: true
